baseURL = 'http://plonkbook.org/'
languageCode = 'en-us'
title = 'Handbook'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true
  BookMenuBundle = '/menu'
